export const LOG_ITEMS = [
  {
    date: '2026/10/12',
    category: 'Talk',
    title: '気持ちぃ〜角丸 Squircles',
    subTitle: 'フロントエンドカンファレンス関西で登壇',
    href: '/slides/squircles/',
  },
  {
    date: '2026/06/26',
    category: 'Blog',
    title: 'Trying',
    href: '/blog/trying',
  },
  {
    date: '2026/06/15',
    category: 'Talk',
    title: 'スタートアップ4社と考える、ドメイン理解の方法論',
    subTitle: '',
    href: 'https://resilire.connpass.com/event/391602',
  },
  {
    date: '2026/06/06',
    category: 'Talk',
    title: '「おすすめ」 はなぜ信用されないのか　〜 信頼を築くUI/UX設計 〜',
    subTitle: 'フロントエンド・PHPカンファレンス北海道2026で登壇',
    href: 'https://fortee.jp/frontend-phpcon-do-2026/proposal/6cd24c56-8f89-4df0-a4f6-83f8be3ec255',
  },
  {
    date: '2026/04/01',
    category: 'Work',
    title: 'Timee, Inc.',
    subTitle: 'Product Engineer',
    href: 'https://corp.timee.co.jp/',
  },
  {
    date: '2026/03/26',
    category: 'Talk',
    title: '機能を売るな、対価を届けろ',
    subTitle: '新卒N年目のLT交流会！好きな技術を語ろう！',
    href: 'https://fresh-engineers.connpass.com/event/386529',
  },
  {
    date: '2026/03/22',
    category: 'Blog',
    title: 'Guiding Principles v0',
    href: '/blog/guiding-principles-v0',
  },
  {
    date: '2026/03/09',
    category: 'Blog',
    title: 'What to Sell',
    subTitle: '顧客は機能を買わない。求める3つの価値',
    href: '/blog/what-to-sell',
  },
  {
    date: '2026/01/10',
    category: 'Event',
    title: 'BuriKaigi 2026 に参加',
    href: 'https://x.com/_ryu1013/status/2009804689764954509',
  },
  {
    date: '2025/12/21',
    category: 'Blog',
    title: 'TanStack DBってなに？',
    subTitle: 'TanStack Queryと比較しながら理解する「クライアントDB」という選択',
    href: 'https://zenn.dev/r1013t/articles/396a10c6025205',
  },
  {
    date: '2025/12/13',
    category: 'Blog',
    title: 'Speed is Power...?',
    subTitle: 'プロダクト開発で本当に加速すべきもの',
    href: '/blog/speed-is-power',
  },
  {
    date: '2025/12/07',
    category: 'Blog',
    title: 'Less, but better',
    href: '/blog/less-but-better',
  },
  {
    date: '2025/06/07',
    category: 'Hackathon',
    title: 'Hack1グランプリ Designship賞',
    subTitle: 'ヒトとAIが混ざり合う新感覚ポッドキャストサービスを開発し、Designship賞を受賞。',
    href: 'https://x.com/_ryu1013/status/1931325850441716015?s=20',
  },
  {
    date: '2025/03/01',
    category: 'Intern',
    title: 'Timee, Inc.',
    subTitle: 'Web Engineer',
    href: 'https://corp.timee.co.jp/',
  },
  {
    date: '2025/02/27',
    category: 'Blog',
    title: '現場で感じた価値：PR TIMESインターンの記録',
    href: 'https://developers.prtimes.com/2025/02/27/prtimes_intern/',
  },
  {
    date: '2025/02/21',
    category: 'Blog',
    title: 'Vitest Browser Modeを活用してブラウザをモックするコードを削除した話',
    href: 'https://developers.prtimes.com/2025/02/21/vitest-browser-mode/',
  },
  {
    date: '2024/12/01',
    category: 'Intern',
    title: 'PR TIMES Corporation',
    subTitle: 'Web Frontend Engineer',
    href: 'https://prtimes.jp/',
  },
  {
    date: '2024/09/16',
    category: 'Hackathon',
    title: 'Tech.SummerCamp 最優秀賞',
    subTitle: '様々なアプリの通知をまとめるサービスを開発し最優秀賞を受賞し30万円を獲得。',
    href: 'https://x.com/_ryu1013/status/1835585461995348001?s=20',
  },
  {
    date: '2024/05/05',
    category: 'Education',
    title: 'Microsoft ゼミ',
    subTitle: 'Azure OpenAI Service を活用し、学生が生成 AI アプリケーション開発を実施',
    href: 'https://www.microsoft.com/ja-jp/microsoft-cloud/blog/microsoft-in-business/2024/04/05/case-study-utilization-of-azure-openai-service-by-students/',
  },
  {
    date: '2024/02',
    category: 'Intern',
    title: 'Zeroichi Laboratory, Inc.',
    subTitle: 'Software Engineer',
    href: 'https://01lab.co.jp/',
  },
  {
    date: '2022/04/01',
    category: 'Education',
    title: 'TECH.C. 入学',
    href: 'https://www.tech.ac.jp/',
  },
] as const;

export type LogItem = (typeof LOG_ITEMS)[number];
